export const T = {
  bg: "#FAF9F7",
  card: "#FFFFFF",
  cardBorder: "#EDE9E3",
  text: "#2D2B28",
  textMid: "#6B6560",
  textLight: "#9C9590",
  textFaint: "#C4BEB8",
  accent: "#C4704B",
  accentLight: "#E8A47A",
  accentBg: "#FDF3ED",
  accentBorder: "#F0D4C3",
  green: "#5B8C6A",
  blue: "#5B7FA6",
  amber: "#B8863B",
  red: "#B85B5B",
  purple: "#8B6BAD",
  tagBg: "#F3F0EC",
  warm1: "#F5E6D3",
  warm2: "#E8D5C4",
};
export const ROLES = [
  {
    title: "Head of Talent Acquisition",
    company: "First",
    companyDesc: "AI-powered recruitment technology start-up. 5 employees at hire. Building tools to help in-house teams manage application volume and improve hiring quality.",
    companyPills: ["High Growth Start-up", "AI CV Screening Tech", "5 Employees"],
    skillPills: ["Product Strategy", "Go-to-Market", "Founding Team", "AI Tooling"],
    roleContext: "First non-technical hire in a 5-person founding team building AI recruitment software. Owning both sides - shaping the product roadmap from a practitioner's perspective while building the go-to-market motion from scratch. Running customer discovery, leading sales conversations, creating content, and hiring the early commercial team.",
    duration: "1y 5m",
    period: "Sep 2023 - Present",
    type: "In-House",
    color: T.blue,
    logo: "/first-logo.png",
    logoFallback: "F",
    highlights: [
      "Shaped product direction from a recruiter's perspective - the only practitioner on the founding team.",
      "Ran 40+ customer discovery calls with TA leaders to validate product-market fit.",
      "Built the GTM strategy and sales playbook - converted 12 pilot customers in 6 months.",
      "Created all product content, demos, and sales collateral from scratch.",
      "Designed the onboarding flow that cut customer time-to-value from 2 weeks to 3 days.",
      "Hired the first 10 team members as the company grew from 5 to 15.",
    ],
    progression: { count: 1, path: "Founding Hire (10 months) → Head of Talent Acquisition (7 months)" },
  },
  {
    title: "Senior Talent Partner",
    company: "Nexus Bank",
    companyDesc: "Series F digital bank. £4.5bn valuation, 2,500+ employees. 70% of headcount in engineering. FCA-regulated, UK and European markets.",
    companyPills: ["Fintech", "£4.5bn Series F", "2,500 Employees"],
    skillPills: ["Tech Hiring", "Direct Sourcing", "Stakeholder Management"],
    roleContext: "Embedded in the engineering org as the sole recruiter covering backend, platform, and infrastructure across 4 squads. Partnered with 11 hiring managers on role scoping, market mapping, and offer strategy. Managed the full cycle from sourcing through to close, with a focus on reducing time-to-offer and eliminating agency dependency entirely.",
    duration: "2y 8m",
    period: "Jan 2021 - Aug 2023",
    type: "In-House",
    color: T.green,
    logo: "data:image/svg+xml," + encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><rect width="100" height="100" rx="14" fill="#0C2416"/><circle cx="38" cy="50" r="22" fill="#27775A"/><circle cx="62" cy="50" r="22" fill="#4ADE80" opacity="0.55"/></svg>'),
    logoFallback: "NB",
    highlights: [
      "Hired 95 engineers in 2.5 years - 70% sourced directly, zero through agencies.",
      "93% 12-month retention rate across all hires, beating the company average by 10 points.",
      "Eliminated agency dependency for the engineering org - saving an estimated £450k+ in fees.",
      "Designed and ran the company's first sourcing bootcamp - upskilled 6 new recruiters.",
      "Built a brand new platform team from 0 to 14 engineers in 5 months.",
      "Rebuilt the candidate experience survey - NPS jumped from 64 to 86 company-wide.",
    ],
    progression: { count: 1, path: "Talent Partner (12 months) → Senior Talent Partner (20 months)" },
    leaving: "Headhunted by First to build their TA function from scratch.",
  },
  {
    title: "Embedded Senior Recruiter",
    company: "Harmon Search",
    companyDesc: "Boutique RPO and embedded recruitment provider, Shoreditch. 25 consultants. Series A to Series C clients across London. Engineering and product placements.",
    companyPills: ["Embedded RPO", "Series A-C Clients", "25 Employees"],
    skillPills: ["Tech Hiring", "Client Management", "Pipeline Building"],
    roleContext: "Placed inside VC-backed startups as an extension of their internal TA teams, working on-site and operating as if in-house. Managed the full recruitment cycle for software engineering roles, from intake and sourcing through to offer negotiation. Built candidate pipelines, ran stakeholder calibration sessions, and trained junior consultants across multiple client accounts.",
    duration: "2y 10m",
    period: "Mar 2018 - Dec 2020",
    type: "Embedded RPO",
    color: T.amber,
    logo: "data:image/svg+xml," + encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><rect width="100" height="100" rx="14" fill="#2E1A06"/><circle cx="44" cy="44" r="20" fill="none" stroke="#D4A04A" stroke-width="6"/><circle cx="44" cy="44" r="7" fill="#D4A04A"/><line x1="59" y1="59" x2="78" y2="78" stroke="#F5DEB3" stroke-width="8" stroke-linecap="round"/></svg>'),
    logoFallback: "HS",
    highlights: [
      "Billed £540k+ over 2.5 years - top biller 7 out of 10 quarters.",
      "Placed 120+ candidates with a 92% retention rate at 12 months.",
      "Won 18 new client accounts through candidate referrals alone - zero cold outreach.",
      "Ran a 12-hire embedded project for a Series A fintech - completed 2 weeks ahead of schedule.",
      "Built a candidate community of 2,000+ engineers through events, dinners, and content.",
      "Mentored 3 junior consultants - all hit target within their first 6 months.",
    ],
    progression: { count: 1, path: "Consultant (14 months) → Senior Consultant (20 months)" },
    leaving: "Wanted to be part of the teams I was hiring for. Made the jump to in-house.",
  },
  {
    title: "Recruitment Consultant",
    company: "Sterling Recruitment",
    companyDesc: "Global recruitment firm, £1.5bn revenue. Technology division, London. 5,000+ employees across 30 countries.",
    companyPills: ["Global Agency", "£1.5bn Revenue", "5,000 Employees"],
    skillPills: ["High Volume", "Contract & Perm", "Business Development"],
    roleContext: "Graduate entry into high-volume agency recruitment, covering contract and permanent technology roles across the South East. 80+ calls a day from week one, managing the full cycle from business development and job qualification through to sourcing, interviewing, and closing. Learned the fundamentals of sales, negotiation, and candidate management at pace.",
    duration: "1y 8m",
    period: "Jul 2016 - Feb 2018",
    type: "Agency",
    color: T.red,
    logo: "data:image/svg+xml," + encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><rect width="100" height="100" rx="14" fill="#2E1010"/><path d="M30 60L50 38L70 60" fill="none" stroke="#E88888" stroke-width="7" stroke-linecap="round" stroke-linejoin="round"/><path d="M30 76L50 54L70 76" fill="none" stroke="#F5C4C4" stroke-width="7" stroke-linecap="round" stroke-linejoin="round"/></svg>'),
    logoFallback: "SR",
    highlights: [
      "Billed £220k in second year - 120% of target, up from 65% in year one.",
      "Fastest in the cohort to make a placement (19 days from desk start).",
      "Placed 55 candidates across contract and permanent roles.",
      "Built an early specialism in DevOps and cloud infrastructure before most agencies had a dedicated desk.",
    ],
    progression: { count: 1, path: "Trainee (11 months) → Recruitment Consultant (9 months)" },
    leaving: "Outgrew the big-firm model. Wanted a smaller team where I could own the full desk.",
  },
];
export const RECOMMENDATIONS = [
  { name: "Priya Sharma", role: "Head of TA", text: "Phil demo'd the product and within five minutes I knew he'd actually done the job. He wasn't selling - he was explaining how he'd solve problems I hadn't even told him about yet.", relation: "Customer @ First" },
  { name: "Marcus Chen", role: "Staff Engineer", text: "Phil sent me two sentences about why I'd be a good fit, both specific to things on my profile nobody else had noticed. Three years later I'm still here.", relation: "Candidate @ Nexus Bank" },
  { name: "Tom Okafor", role: "Engineering Director", text: "Phil hired 40 of my engineers and I'd trust every single one of them again. He understood what good looked like for my team better than most of the team did.", relation: "Hiring Manager @ Nexus Bank" },
  { name: "Lucy Ward", role: "Recruitment Consultant", text: "Phil trained me when I joined and he's the reason I'm still in recruitment. I hit target in my first 6 months because of how he set me up.", relation: "Direct Report @ Harmon Search" },
];
export const BUILD_TILES = [
  { category: "Agents & Builds", title: "Hiring Plan Agent", desc: "Feed it a headcount target, budget, and org structure. It generates a phased hiring plan with timelines, sourcing strategy, and recruiter capacity needs.", type: "AI Agent", icon: "🤖", color: T.blue, modal: "prospect", linkLabel: "View project", tags: ["Claude Code", "Claude API", "Node.js", "Vercel"] },
  { category: "Automation & Process Improvement", title: "Feedback Chaser Automation", desc: "Polls the ATS for outstanding hiring manager feedback. If none submitted after 48 hours, it auto-chases them on Slack with context and a direct link.", type: "Automation", icon: "⚡", color: T.green, modal: "sheets", linkLabel: "View project", tags: ["Zapier", "Greenhouse API", "Slack"] },
  { category: "Agents & Builds", title: "CV Invaders", desc: "Vibe coded Space Invaders with a recruitment twist. Agency vs in-house leaderboard. Built for fun, shared for laughs. This is a live real game - click to play!", type: "Arcade Game", icon: "👾", color: T.purple, url: "https://cv-invaders.vercel.app/", linkLabel: "Play", tags: ["Claude Code", "Supabase", "GitHub", "JavaScript"] },
  { category: "Automation & Process Improvement", title: "Recruiter Process Survey", desc: "Surveyed the recruiting team quarterly to surface process pain points. Used the data to prioritise fixes, remove bottlenecks, and drive measurable improvement in time-to-hire and recruiter satisfaction.", type: "RecOps", icon: "📋", color: T.accent, modal: "recops", linkLabel: "View project", tags: ["RecOps", "Google Forms", "Data Analysis"] },
  { category: "Content & Community", title: "Vibe-coded CV Guide", desc: "Click here to drop some love on the post to spread the word and get more recruiters vibe coding! The more likes, the more people see it.", type: "Shameless Plug", icon: "📄", color: T.accent, url: "https://www.linkedin.com/in/jamiejaylyons/", linkLabel: "Like the post", tags: ["Recruiter Training", "Vibe Coding", "Future of Work"] },
  { category: "Content & Community", title: "Weekly Recruitment Content", desc: "I post weekly hiring breakdowns. Hiring podcasts, hiring books, hiring events and much more, all recruitment related. Click to check out my content!", type: "Shameless Plug v2", icon: "✍️", color: T.blue, url: "https://www.linkedin.com/in/jamiejaylyons/recent-activity/all/", linkLabel: "See posts", tags: ["Recruitment Content", "Books", "Podcasts", "Events"] },
];
export const STATS = [
  { value: 300, suffix: "+", label: "Career Hires", prefix: "" },
  { value: 19, suffix: "d", label: "Avg Time-to-Offer", prefix: "" },
  { value: 93, suffix: "%", label: "Retention Rate", prefix: "" },
  { value: "Series A - F", label: "Companies Scaled", isText: true },
];
